#!/usr/bin/env python3
"""Generate the manual's option reference from the source of truth.

The interface is described exactly once, in the OPTIONS table in
src/ADZE_pfile.cpp, which the command-line parser, the paramfile parser,
--help and --write-template all read. This script parses that table and emits
options.tex, so the manual cannot document a flag the program does not have --
which is how the 1.0 manual and paramfile template came to disagree with the
1.0 parser.

    ./doc/gen_options.py src/ADZE_pfile.cpp doc/options.tex
"""
import re
import sys

# {ID, "KEYWORD"|0, "--long", "-short"|0, OPT_TYPE, "ARG"|0, "Section", "help"}
ENTRY = re.compile(
    r"\{\s*(\w+)\s*,\s*"
    r'(0|"[^"]*")\s*,\s*'
    r'(0|"[^"]*")\s*,\s*'
    r'(0|"[^"]*")\s*,\s*'
    r"(OPT_\w+)\s*,\s*"
    r'(0|"[^"]*")\s*,\s*'
    r'"([^"]*)"\s*,\s*'
    r'"((?:[^"\\]|\\.)*)"\s*\}',
    re.S)

TYPE_NAME = {"OPT_INT": "int", "OPT_DOUBLE": "float", "OPT_STRING": "string",
             "OPT_BOOL": "boolean"}


def unquote(tok):
    return None if tok == "0" else tok[1:-1]


def tex_escape(s):
    for a, b in (("\\", r"\textbackslash{}"), ("_", r"\_"), ("&", r"\&"),
                 ("%", r"\%"), ("#", r"\#"), ("$", r"\$"), ("{", r"\{"),
                 ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")):
        s = s.replace(a, b)
    return s


def parse(path):
    with open(path) as fh:
        src = fh.read()
    start = src.index("const OptSpec OPTIONS[] = {")
    end = src.index("\n};", start)
    rows = []
    for m in ENTRY.finditer(src[start:end]):
        rows.append({
            "id": m.group(1),
            "key": unquote(m.group(2)),
            "long": unquote(m.group(3)),
            "legacy": unquote(m.group(4)),
            "type": TYPE_NAME[m.group(5)],
            "arg": unquote(m.group(6)),
            "section": m.group(7),
            "help": m.group(8).replace('\\"', '"'),
        })
    if not rows:
        raise SystemExit("no OPTIONS entries parsed from %s" % path)
    return rows


def emit(rows, out):
    sections = []
    for r in rows:
        if r["section"] not in sections:
            sections.append(r["section"])

    with open(out, "w") as fh:
        fh.write("% Generated by doc/gen_options.py from src/ADZE_pfile.cpp.\n"
                 "% Do not edit; edit the OPTIONS table instead.\n")
        for sec in sections:
            fh.write("\n\\subsubsection{%s options}\n\n" % tex_escape(sec))
            fh.write("\\begin{description}[style=nextline,leftmargin=1em]\n")
            for r in (x for x in rows if x["section"] == sec):
                flags = ["\\texttt{%s%s}" % (
                    tex_escape(r["long"]),
                    " \\textit{%s}" % tex_escape(r["arg"]) if r["arg"] else "")]
                if r["legacy"]:
                    flags.append("\\texttt{%s}" % tex_escape(r["legacy"]))
                if r["key"]:
                    flags.append("\\texttt{%s} (paramfile)" % tex_escape(r["key"]))
                fh.write("\\item[%s] \\hfill \\textit{%s}\\\\ %s\n" % (
                    ", ".join(flags), r["type"], tex_escape(r["help"])))
            fh.write("\\end{description}\n")

    return len(rows), sections


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    n, secs = emit(parse(sys.argv[1]), sys.argv[2])
    print("%s: %d options in %d sections" % (sys.argv[2], n, len(secs)))
